### PR TITLE
Add robots.txt

### PR DESCRIPTION
**Pull request by flexbox**
Google needs some ❤️

### CODE REVIEW

**Comment by flexbox** [comment]
Arf sh$t I just see 
https://github.com/lgiraudel/adopteungit/pull/3

**Comment by flexbox** [comment]
PR updated!

**Comment by lgiraudel** [comment]
I think I should find a way to generate a sitemap first...

But thanks for the PR, it's a good reminder :)

**Comment by flexbox** [comment]
@HugoGiraudel Just push `jekyll-sitemap` 🚀

**Comment by lgiraudel** [comment]
Yeah but the PR has been cancelled by Hugo.

I will add the jekyll-sitemap gem.

**Pull request merged**
